FROM n8nio/n8n

WORKDIR /home/node/

ENV TZ=Europe/Brussels
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=estelle
ENV N8N_BASIC_AUTH_PASSWORD=yourStrongPassword
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=http
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_PORT=5432

CMD ["n8n"]
