FROM n8nio/n8n
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=litchie
ENV N8N_BASIC_AUTH_PASSWORD=saxzesiuer
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=http
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_PORT=5432
ENV TZ=Europe/Brussels

CMD ["n8n"]
